### ISSUE TITLE
依赖失败！是不是服务器炸了。。

### ISSUE THREAD

**Issue by yangkile** [barryhappy/TEmptyView#1]
试了好几次

**Comment by barryhappy** [comment]
compile路径写错了……好尴尬。
o(╯□╰)o
`compile 'com.barryzhang:temptyview:0.0.1'  `是正确的。


'com.barryzhang.temptyview:0.0.1'  =>  'com.barryzhang:temptyview:0.0.1'

**Comment by imknown** [comment]
这标题笑死我了.. 问题可以关闭了..
